### ISSUE TITLE
Not able to setup bot

### ISSUE THREAD

**Issue by aftabkh505** [nastyzera/Torrent-Drive-Telegram-Bot-Using-Colab#1]
my config.cg
[creds]
token = 1296597745:AAFVBZe9M9L6PiLgA7SBhd5dALDsdjEjiKc

"error while running !python server.py-

Traceback (most recent call last):
  File "server.py", line 68, in <module>
    reply = make_reply(message)
  File "server.py", line 54, in make_reply
    return reply
UnboundLocalError: local variable 'reply' referenced before assignment"

**Comment by ghost** [comment]
You have use ".cg" extension for config file ,use ".cfg" ,it's a config file
